// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightBlog from "starlight-blog";
import starlightThemeChameleon from "starlight-theme-chameleon";
import starlightSidebarSections from "./src/plugins/sidebar-sections.ts";
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  site: "https://legacycoder.net",
  vite: {
    server: {
      // Morph task instances expose the dev server as
      // dev-<instance>.http.cloud.morph.so; Vite rejects unknown hosts.
      allowedHosts: [".http.cloud.morph.so"],
    },
  },
  integrations: [
    starlight({
      title: "Guido Schlabitz",
      customCss: ["./src/styles/pfeffer.css", "./src/styles/bio.css", "./src/styles/header.css", "./src/styles/skills.css", "./src/styles/recipes.css"],
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/gschlabitz" },
        { icon: "laptop", label: "Upwork", href: "https://www.upwork.com/freelancers/~01385cf1007a0ae63d" },
        { icon: "twitter", label: "Twitter", href: "https://x.com/legacy__coder" },
        // { icon: "discord", label: "Discord", href: "https://discord.com/????????????????????????" },
        { icon: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/guido-schlabitz/" },
        { icon: "email", label: "Email", href: "mailto:hello@legacycoder.net" },
      ],
      components: {
        // Renders starlight-blog's header link plus our own Links link.
        SiteTitle: "./src/components/SiteTitle.astro",
        LanguageSelect: "./src/components/LanguageSelect.astro",
        // Stock social icons, but external profiles open in a new tab.
        SocialIcons: "./src/components/SocialIcons.astro",
        // Stock hero plus the CRT typing backdrop behind the whole page.
        Hero: "./src/components/Hero.astro",
      },
      defaultLocale: "root",
      locales: {
        root: { label: "English", lang: "en" },
        de: { label: "Deutsch", lang: "de" },
      },
      plugins: [
        starlightBlog({
          title: { en: "Blog", de: "Blog" },
          navigation: "none",
          authors: {
            guido: {
              name: "Guido Schlabitz",
            },
          },
        }),
        // Blog posts are Docs pages, so Starlight's autogenerated sidebar
        // lists every one of them and buries the actual sections.
        starlightSidebarSections({
          exclude: ["blog"],
          labels: { "llm-notebook": "LLM Notebook", "recipes": "Recipes", workarounds: "Workarounds" },
        }),
        // After starlightBlog so Chameleon sees the final component map (ADR 0003).
        starlightThemeChameleon({
          skins: ["nordic", "catppuccin", "home-computer"],
          skinSelector: "icon",
          themeSelector: "icon",
        }),
      ],
    }),
    react(),
  ],
});
