// @ts-check
import { readdirSync, readFileSync } from "node:fs";
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightBlog from "starlight-blog";
import starlightThemeChameleon from "starlight-theme-chameleon";
import react from "@astrojs/react";

const DOCS = "./src/content/docs";

// Sections the pages sidebar leaves alone: `blog`, because Blog posts are Docs
// pages and Starlight's autogenerated sidebar would list all ~166 of them,
// burying everything else (starlight-blog's `navigation` option governs header
// links, not this); `de`, because that's the locale, not a section.
const NOT_A_SECTION = new Set(["blog", "de"]);

// Drafts are absent from the production build, so a sidebar entry pointing at
// one fails `astro build` outright. They stay listed while developing, which
// is the only place they exist at all.
const showDrafts = process.env.NODE_ENV === "development";

// Derived rather than hand-listed so that adding a page, or flipping one to
// `draft: true`, never needs a matching edit here — the hand-written version
// of this list turns a forgotten draft flag into a broken build.
//
// This snapshot is taken once, when the config loads, so adding or renaming a
// *top-level* page needs a dev server restart to show up. Everything inside a
// section is a Starlight `autogenerate` group and still hot-reloads.
const sidebar = readdirSync(DOCS, { withFileTypes: true })
  .flatMap((entry) => {
    if (NOT_A_SECTION.has(entry.name)) return [];
    if (entry.isDirectory()) return [{ key: entry.name, directory: true }];
    if (!/\.mdx?$/.test(entry.name)) return [];
    const key = entry.name.replace(/\.mdx?$/, "");
    const draft = /^draft:\s*true\s*$/m.test(readFileSync(`${DOCS}/${entry.name}`, "utf8"));
    return draft && !showDrafts ? [] : [{ key, directory: false }];
  })
  // The landing page sorts first; everything else alphabetically, so the order
  // matches what autogeneration used to produce.
  .sort((a, b) => (a.key === "index" ? "" : a.key).localeCompare(b.key === "index" ? "" : b.key))
  .map((entry) =>
    entry.directory
      ? { label: entry.key, items: [{ autogenerate: { directory: entry.key } }] }
      : { slug: entry.key === "index" ? "" : entry.key },
  );

// https://astro.build/config
export default defineConfig({
  site: "https://legacycoder.net",
  vite: {
    server: {
      // Morph task instances expose the dev server as
      // dev-<instance>.http.cloud.morph.so; Vite rejects unknown hosts.
      allowedHosts: [".http.cloud.morph.so"],
    },
  },
  integrations: [
    starlight({
      title: "Guido Schlabitz",
      customCss: ["./src/styles/pfeffer.css", "./src/styles/bio.css", "./src/styles/header.css"],
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/gschlabitz" },
        { icon: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/guido-schlabitz/" },
        { icon: "email", label: "Email", href: "mailto:hello@legacycoder.net" },
      ],
      components: {
        // Renders starlight-blog's header link plus our own Links link.
        SiteTitle: "./src/components/SiteTitle.astro",
        LanguageSelect: "./src/components/LanguageSelect.astro",
        // Stock social icons, but external profiles open in a new tab.
        SocialIcons: "./src/components/SocialIcons.astro",
        // Stock hero plus the CRT typing backdrop behind the whole page.
        Hero: "./src/components/Hero.astro",
      },
      defaultLocale: "root",
      locales: {
        root: { label: "English", lang: "en" },
        de: { label: "Deutsch", lang: "de" },
      },
      sidebar,
      plugins: [
        starlightBlog({
          title: { en: "Blog", de: "Blog" },
          navigation: "none",
          authors: {
            guido: {
              name: "Guido Schlabitz",
            },
          },
        }),
        // After starlightBlog so Chameleon sees the final component map (ADR 0003).
        starlightThemeChameleon({
          skins: ["nordic", "catppuccin", "home-computer"],
          skinSelector: "select",
          themeSelector: "icon",
        }),
      ],
    }),
    react(),
  ],
});
