// Regenerate the tile CSS from the sheets registered in
// src/data/tilesheets.yaml. For each sheet this emits:
//
//   .ts-<name>        — binds the sheet image and its grid geometry
//   .ts-<name>.t-<i>  — selects tile <i>, numbered row-major like Kenney's
//                       individual Tiles/tile_00NN.png files
//
// into src/styles/tiles.css, plus a src/data/tilesheets.json with the
// measured geometry for Astro components (e.g. TileSheetChart.astro).
//
// Tiles scale through the --px custom property (the CSS length of one art
// pixel); keep it a whole number of CSS px or tile edges will bleed.
//
// Usage: npm run tile-css

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = resolve(root, 'src/data/tilesheets.yaml');
const cssPath = resolve(root, 'src/styles/tiles.css');
const jsonPath = resolve(root, 'src/data/tilesheets.json');

// Width and height live in the PNG's IHDR chunk, big-endian, right after
// the 8-byte signature and the chunk length/type — no image library needed.
function pngSize(path) {
  const buffer = readFileSync(path);
  const signature = '\x89PNG\r\n\x1a\n';
  if (buffer.subarray(0, 8).toString('latin1') !== signature) {
    throw new Error(`${path} is not a PNG file`);
  }
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

const manifest = parse(readFileSync(manifestPath, 'utf8'));

const sheets = manifest.map((entry) => {
  const { width, height } = pngSize(resolve(root, entry.file));
  if (width % entry.tileSize !== 0 || height % entry.tileSize !== 0) {
    throw new Error(
      `${entry.name}: ${width}×${height} is not a multiple of ${entry.tileSize} — ` +
        `not a packed sheet? Use the *_packed.png variant (no spacing between tiles).`,
    );
  }
  return {
    ...entry,
    url: entry.file.replace(/^public/, ''),
    cols: width / entry.tileSize,
    rows: height / entry.tileSize,
  };
});

const lines = [
  '/* Generated by scripts/tile-css.mjs from src/data/tilesheets.yaml.',
  '   Do not edit — run `npm run tile-css` instead. */',
  '',
  '/* One art pixel, as a CSS length. Integer multiples only: fractional',
  '   scales sample across tile boundaries and bleed neighboring tiles. */',
  ':root {',
  '  --px: 2px;',
  '}',
  '@media (min-width: 800px) {',
  '  :root {',
  '    --px: 3px;',
  '  }',
  '}',
  '@media (min-width: 1400px) {',
  '  :root {',
  '    --px: 4px;',
  '  }',
  '}',
  '',
  '.ts {',
  '  --tx: 0;',
  '  --ty: 0;',
  '  display: inline-block;',
  '  width: calc(var(--ts-size) * var(--px));',
  '  height: calc(var(--ts-size) * var(--px));',
  '  background-size: calc(var(--ts-cols) * var(--ts-size) * var(--px))',
  '    calc(var(--ts-rows) * var(--ts-size) * var(--px));',
  '  background-position: calc(var(--tx) * var(--ts-size) * var(--px) * -1)',
  '    calc(var(--ty) * var(--ts-size) * var(--px) * -1);',
  '  image-rendering: pixelated;',
  '}',
  '',
  '/* A tilemap-style scene: set --cols and stream tiles in row-major order;',
  '   they wrap into seamless rows on their own. Empty cells are plain',
  '   <span class="ts"></span> (no sheet class → no background). */',
  '.tile-scene {',
  '  /* Default scene ground: the tiles\' own outline color (the most',
  '     frequent opaque pixel in the Kenney sheets), so tile edges and',
  '     empty cells blend into one surface. Override with --scene-bg. */',
  '  background: var(--scene-bg, #434a5f);',
  '  display: grid;',
  '  grid-template-columns: repeat(var(--cols), max-content);',
  '  width: max-content;',
  '  line-height: 0;',
  '}',
  '',
  '/* HTML content occupying tile cells: place it into the scene grid with',
  '   an inline grid-area (1-based lines: row-start / col-start / row-end /',
  '   col-end). It can share cells with tiles — later items paint on top. */',
  '.tile-text {',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  line-height: 1;',
  "  font-family: 'VT323', ui-monospace, 'SF Mono', Menlo, Consolas, monospace;",
  '  font-size: calc(var(--px) * 9);',
  '  color: var(--tile-text-color, #e7dad4);',
  '}',
];

for (const sheet of sheets) {
  lines.push(
    '',
    `/* ${sheet.name}: ${sheet.cols}×${sheet.rows} tiles of ${sheet.tileSize}px (${sheet.author}, ${sheet.source}) */`,
    `.ts-${sheet.name} {`,
    `  background-image: url('${sheet.url}');`,
    `  --ts-size: ${sheet.tileSize};`,
    `  --ts-cols: ${sheet.cols};`,
    `  --ts-rows: ${sheet.rows};`,
    '}',
  );
  for (let i = 0; i < sheet.cols * sheet.rows; i++) {
    const tx = i % sheet.cols;
    const ty = Math.floor(i / sheet.cols);
    lines.push(`.ts-${sheet.name}.t-${i} { --tx: ${tx}; --ty: ${ty}; }`);
  }
}

writeFileSync(cssPath, lines.join('\n') + '\n');
writeFileSync(jsonPath, JSON.stringify(sheets, null, 2) + '\n');

for (const sheet of sheets) {
  console.log(`${sheet.name}: ${sheet.cols}×${sheet.rows} tiles (${sheet.tileSize}px) from ${sheet.url}`);
}
console.log(`Wrote ${cssPath}`);
console.log(`Wrote ${jsonPath}`);
